//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEmployee()
        {
            this.tbUsers = new HashSet<tbUser>();
        }
    
        public decimal empID { get; set; }
        public string Name { get; set; }
        public string IDCard { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ContactPhone { get; set; }
        public string Gender { get; set; }
        public string CurrentAddress { get; set; }
        public string PerAddress { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Position { get; set; }
        public Nullable<int> photo { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isActivated { get; set; }
    
        public virtual tbPhoto tbPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser> tbUsers { get; set; }
    }
}
