//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGeneralParameter
    {
        public int id { get; set; }
        public string Parameter_type { get; set; }
        public string Parameter_name { get; set; }
        public Nullable<decimal> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy_name { get; set; }
        public Nullable<decimal> modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
