//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPermissionByForm
    {
        public int id { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> canDelete { get; set; }
        public Nullable<bool> canAdd { get; set; }
        public Nullable<bool> canUpdate { get; set; }
        public Nullable<bool> canView { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy_name { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedByName { get; set; }
    }
}
