//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPermission
    {
        public decimal pID { get; set; }
        public string PermissionType { get; set; }
        public Nullable<bool> canAdd { get; set; }
        public Nullable<bool> canUpdate { get; set; }
        public Nullable<bool> canDelete { get; set; }
        public Nullable<bool> canView { get; set; }
        public Nullable<decimal> createdby { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<decimal> modifiedBy { get; set; }
        public string note { get; set; }
        public string UserType { get; set; }
    }
}
