//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTeamWork
    {
        public decimal TeamWorkID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Name { get; set; }
        public string AssignedByID { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
