//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public decimal Userid { get; set; }
        public Nullable<int> UserType { get; set; }
        public string UserName { get; set; }
        public string pwd { get; set; }
        public Nullable<decimal> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string createdByName { get; set; }
        public decimal empId { get; set; }
        public Nullable<bool> isActibe { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> keeplogin { get; set; }
    
        public virtual tbEmployee tbEmployee { get; set; }
        public virtual tbUserType tbUserType { get; set; }
    }
}
