//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GetStudentList
    {
        public decimal stdID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Class { get; set; }
        public string DOB { get; set; }
        public string ContactPhone { get; set; }
        public string Current_Address { get; set; }
        public string Previous_Address { get; set; }
        public string Descriptions { get; set; }
        public string Father_name { get; set; }
        public string Mother_name { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
