//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GetClassList
    {
        public int ClassID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Capacity { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string CreatedDate { get; set; }
        public string code { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
