//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GetPermissionByFormList
    {
        public int id { get; set; }
        public string FormName { get; set; }
        public string FormType { get; set; }
        public string module { get; set; }
        public Nullable<int> PermissionID { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public bool CanAdd { get; set; }
        public bool CanDelete { get; set; }
        public bool CanUpdate { get; set; }
        public bool CanView { get; set; }
    }
}
