//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_UserProfile
    {
        public decimal Userid { get; set; }
        public string UserType { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string createdByName { get; set; }
        public Nullable<decimal> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public byte[] Photo { get; set; }
        public string ContactPhone { get; set; }
        public string Gender { get; set; }
        public string Position { get; set; }
        public string pwd { get; set; }
    }
}
